plugins:
  rubocop:
    enabled: true
    channel: rubocop-0-74
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  fixme:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - ruby
  eslint:
    enabled: true
    channel: "eslint-5"
    config:
      extensions:
        - .js
        - .jsx
ratings:
  paths:
    - app/**
    - lib/**
    - "**.rb"
exclude_paths:
  - db/
  - spec/
  - config/
  - vendor/
  - scripts/
  - "**.csv"
  - "**.yml"
  - "**.xml"
