plugins:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - javascript
        - ruby
    # exclude_paths:
    #   - "app/controllers/"
  eslint:
    enabled: true
    config:
      extensions:
        - .js
        - .jsx
  fixme:
    enabled: true
  reek:
    enabled: true
  rubocop:
    enabled: true
    channel: rubocop-1-63
  markdownlint:
    enabled: true
  rubymotion:
    enabled: true
  reek:
    enabled: true
  standard:
    enabled: true
ratings:
  paths:
    - "app/**"
    - "lib/**"
    - "**.rb"
exclude_paths:
  - "db/"
  - "spec/"
  - "config/"
  - "public/"
  - "vendor/"
