require:
  - rubocop-capybara
  - rubocop-rails
  - rubocop-rspec

AllCops:
  UseCache: false
  TargetRubyVersion: 3.3
  NewCops: enable
  Exclude:
    - "vendor/**/*"
    - "db/**/*"
    - "config/**/*"
    - "bin/*"
    - "**/*.erb"
Metrics/BlockLength:
  Exclude:
    - "config/environments/*.rb"
    - "spec/**/*"
Style/Documentation:
  Description: Document classes and non-namespace modules.
  Enabled: false
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
Style/FrozenStringLiteralComment:
  Enabled: false
RSpec/MultipleExpectations:
  Max: 5
RSpec/ExampleLength:
  Max: 50
