version: "3"

volumes:
  postgres_data:
    driver: local
  bundle_cache:
    driver: local

services:
  postgres:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    logging:
      driver: "none"
    ports:
      - "${POSTGRES_PORT}:5432"
    hostname: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  web-tracking:
    build:
      context: .
    tty: true
    stdin_open: true
    env_file:
      - ./.env
    depends_on:
      - postgres
    links:
      - postgres
    ports:
      - "${RAILS_PORT}:3000"
    volumes:
      - ./:/app
      - bundle_cache:/bundle
