name: tracking

volumes:
  postgres_data:

services:
  ###########################
  # SHARED POSTGRES CLUSTER #
  ###########################
  postgres:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # logging:
    #   driver: "none"
    ports:
      - "5432:5432"
    hostname: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  tracking:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "tracking"
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - ./.env
    # logging:
    #   driver: "none"
    hostname: tracking
