version: "3"

services:
  postgres:
    image: postgres:11
    logging:
      driver: "none"
    ports:
      - "${POSTGRES_PORT}:5432"

  web-tracking:
    build:
      context: .
    tty: true
    stdin_open: true
    depends_on:
      - postgres
    links:
      - postgres
    ports:
      - "${RAILS_PORT}:3000"
